---
all:
  children:
    frontend:
      hosts:
        vm1:
          ansible_host: 34.16.94.246
          ansible_user: abduss
    backend:
      hosts:
        vm2:
          ansible_host: 34.45.37.144
          ansible_user: abduss
  vars:
    ansible_python_interpreter: /usr/bin/python3
    project_name: dapmeet
    domain_name: dapmeet.local

