---
galaxy_info:
  role_name: rsyslog
  author: Abdurakhimov Abdussalam
  description: Configure rsyslog for log forwarding and custom log files
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []


