---
galaxy_info:
  author: Abdurakhimov Abdussalam
  description: Install Docker and manage containers for Dapmeet project
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []

collections:
  - community.docker

